CREATE TABLE IF NOT EXISTS Users( 
	ID SERIAL PRIMARY KEY NOT NULL, 
	NAME TEXT NOT NULL, 
	PHONE_NO TEXT NOT NULL,
	EMAIL TEXT NOT NULL UNIQUE,
	ADDRESS_LINE_1 TEXT NOT NULL,
	ADDRESS_LINE_2 TEXT NOT NULL,
	LANDMARK TEXT NOT NULL,
	CITY TEXT NOT NULL, 
	PINCODE TEXT NOT NULL,
	LATITUDE REAL,
	LONGITUDE REAL
);

CREATE TABLE IF NOT EXISTS Restaurant( 
	ID SERIAL PRIMARY KEY NOT NULL, 
	OWNER_NAME TEXT NOT NULL,
	RESTAURANT_NAME TEXT NOT NULL, 
	PHONE_NO TEXT NOT NULL,
	EMAIL TEXT NOT NULL UNIQUE,
	ADDRESS_LINE_1 TEXT NOT NULL,
	ADDRESS_LINE_2 TEXT NOT NULL,
	LANDMARK TEXT NOT NULL,
	CITY TEXT NOT NULL, 
	PINCODE TEXT NOT NULL,
	LATITUDE REAL,
	LONGITUDE REAL
);