CREATE TABLE IF NOT EXISTS Users( 
	USER_ID SERIAL PRIMARY KEY NOT NULL, 
	NAME TEXT NOT NULL, 
	PHONE_NO TEXT NOT NULL,
	EMAIL TEXT NOT NULL UNIQUE,
	ADDRESS_LINE_1 TEXT NOT NULL,
	ADDRESS_LINE_2 TEXT NOT NULL,
	LANDMARK TEXT NOT NULL,
	CITY TEXT NOT NULL, 
	PINCODE TEXT NOT NULL,
	LATITUDE REAL,
	LONGITUDE REAL
);

CREATE TABLE IF NOT EXISTS Restaurant( 
	RESTAURANT_ID SERIAL PRIMARY KEY NOT NULL, 
	OWNER_NAME TEXT NOT NULL,
	RESTAURANT_NAME TEXT NOT NULL, 
	PHONE_NO TEXT NOT NULL,
	EMAIL TEXT NOT NULL UNIQUE,
	ADDRESS_LINE_1 TEXT NOT NULL,
	ADDRESS_LINE_2 TEXT NOT NULL,
	LANDMARK TEXT NOT NULL,
	CITY TEXT NOT NULL, 
	PINCODE TEXT NOT NULL,
	LATITUDE REAL,
	LONGITUDE REAL
);

CREATE TABLE IF NOT EXISTS Dishes( 
	DISH_ID SERIAL PRIMARY KEY NOT NULL, 
	DISH_NAME TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRICE REAL NOT NULL,
	SERVING REAL NOT NULL,
	CUISINE TEXT NOT NULL,
	RESTAURANT_ID INTEGER NOT NULL,
	IMG_URL TEXT,
	CONSTRAINT fk_restaurant FOREIGN KEY(RESTAURANT_ID) REFERENCES Restaurant(RESTAURANT_ID)
);

CREATE TABLE IF NOT EXISTS IMAGE( 
	IMAGE_ID SERIAL PRIMARY KEY NOT NULL, 
	SIZE REAL NOT NULL,
	IMG_DATA BYTEA NOT NULL,
	CONTENT_TYPE TEXT NOT NULL,
	IMG_URL TEXT
);